### ISSUE TITLE
Crashes on Ubuntu 19.10

### ISSUE THREAD

**Issue by merlijn-sebrechts** [popey/zzt-snap#1]
|   |   |
| ------------- |:-------------:|
| Distro and Version       |       Ubuntu 19.10       |
| Xorg or Wayland          |    Xorg  |
| GPU                            |    Intel  |

The game crashes with the following output:

```shell
$ snap run zzt
DOSBox version SVN
Copyright 2002-2017 DOSBox Team, published under GNU GPL.
---
/snap/zzt/4/launcher: line 76:  1195 Segmentation fault      (core dumped) $SNAP/bin/dosbox -conf $SNAP_USER_DATA/dosbox.conf
```

**Comment by popey** [comment]
Thanks for the report. I believe this is now fixed. I just triggered a newer build. So something broke since the 2017 dated build I'd previously published. A little worrying.
I have noticed I'd not got it hooked up to the build service. So I have done that, and updated it for core18 too.

**Comment by merlijn-sebrechts** [comment]
Yes, it works now, thanks!
